---
name: Test JMeter Action

on:
  push:
    branches:
      - master
      - 'feature/adding-reports'
  pull_request:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v1

      - name: Lint all YAML files in the directory
        uses: ibiqlik/action-yamllint@master

      - name: Run JMeter Action
        uses: ./
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
