name: Test Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run jmeter action
      uses: ./
      with:
        testFilePath: tests/sample_test.jmx
        outputLogFilePath: results/results.log
        outputResultsPath: results/test_results.log

    - uses: actions/upload-artifact@v1
      with:
        name: jmeter-test-results
        path: results/