name: Test Action

on:
  push:
    branches: 
      - master
      - 'feature/adding-reports'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run jmeter action
      uses: ./
      with:
        testFilePath: tests/sample_test.jmx
        outputReportsFolder: reports/

    - uses: actions/upload-artifact@v1
      with:
        name: jmeter-test-results
        path: reports/